version: '2'
services:
    simple-app:
        image: simple
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://simple-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=simple
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simple-mongodb:
        extends:
            file: mongodb.yml
            service: simple-mongodb
